services:
  feeds:
    image: dsp8ef9/feeds:latest
    container_name: feeds
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: feeds.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.dev.json:/app/config.dev.json:ro
      - ./gpg:/app/gpg